src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $designation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $Prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $remise;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="produits", orphanRemoval=true ,  cascade={"persist"})
     */
    private $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->Code;
    }

    public function setCode(string $Code): self
    {
        $this->Code = $Code;

        return $this;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getRemise(): ?int
    {
        return $this->remise;
    }

    public function setRemise(?int $remise): self
    {
        $this->remise = $remise;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setProduits($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduits() === $this) {
                $image->setProduits(null);
            }
        }

        return $this;
    }

    
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'produits'=>$produitRepository->findAll(),
        ]);
    }

    #[Route('/produit/detail/{id}', name: 'produit_detail')]
    public function DetailProduit(Produit $produit): Response
    {
        return $this->render('home/detail.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/panier/add/{id}", name="ajout_panier")
     */
    public function addpanier($id, SessionInterface $session)
    {
        $panier = $session->get('panier',[]);
        if(!empty($panier[$id])){
            $panier[$id]++;
        }
        else{
            $panier[$id]=1;
        }
        $session->set('panier', $panier);
       // dd($session->get('panier'));
       return $this->redirectToRoute('home');;
    }

    /**
     * @Route("/produit/panier", name="consulter_pannier")
     */
    public function Pannier(SessionInterface $session, ProduitRepository $prod )
    {
        $panier = $session->get('panier',[]);

        $panierdonner=[];

        foreach ($panier as $id=> $quantite){
            $panierdonner[]=[
                'produit'=>  $prod->find($id),
                'quantite'=> $quantite
            ];
        }
        $total=0;

        foreach($panierdonner as $item)
        {
            // calculer le montant de chaque produit
            $totalitem = $item['produit']->getPrix() * $item['quantite'];
            // clacule de monatant total de tt les produits
            $total+=$totalitem;
        }
        return $this->render('home/panier.html.twig', [
            'paniers'=>$panierdonner,
            'total'=> $total
        ]);
    }

    /**
     * @Route("/add/{id}", name="prod_add")
     */
    public function add(Produit $product, SessionInterface $session)
    {
        // On récupère le panier actuel
        $panier = $session->get("panier", []);
        $id = $product->getId();

        if(!empty($panier[$id])){
            $panier[$id]++;
        }else{
            $panier[$id] = 1;
        }

        // On sauvegarde dans la session
        $session->set("panier", $panier);

        return $this->redirectToRoute("consulter_pannier");
    }

     /**
     * @Route("/remove/{id}", name="prod_remove")
     */
    public function remove(Produit $product, SessionInterface $session)
    {
        // On récupère le panier actuel
        $panier = $session->get("panier", []);
        $id = $product->getId();

        if(!empty($panier[$id])){
            if($panier[$id] > 1){
                $panier[$id]--;
            }else{
                unset($panier[$id]);
            }
        }

        // On sauvegarde dans la session
        $session->set("panier", $panier);

        return $this->redirectToRoute("consulter_pannier");
    }



    /**
     * @Route("/panier/delete/{id}",name="delete_prod")
     */
    public function delete($id, SessionInterface $session)
    {
       $panier= $session->get('panier',[]);
       if (!empty($panier[$id])){
           unset($panier[$id]);
       }
       $session->set('panier',$panier);
       return $this->redirectToRoute('consulter_pannier');
    }

   
}

templates/home/detail.html.twig
{% extends "front.html.twig" %}


{% block body %}


	<h1>Product detail</h1>
    <div class="row">
        <div class="gallery">
            {% set i = 1 %}
            {% for image in produit.images %}
                <img src="{{ asset('uploads/images/product/'~ image.name) }}" alt="{{produit.designation}}" class="gallery__photo gallery__photo--p{{i}}">
                {% set i = i+1 %}
            {% endfor %}
            
        </div>
	</div>

    <div class="row" style="margin-top: 600px;">
        <h3>{{ produit.designation }},   {{ produit.prix }}DT </h3><span style="color: red; font-size: large;"> {{ produit.remise }}%</span>
        <p>{{ produit.description }}</p>
    </div>

{% endblock %}

templates/home/index.html.twig
{% extends 'front.html.twig' %}

{% block body %}

   
        <div class="row" style="margin-top: 20px; ">
             {% for produit in produits %}
                <div class="col-3" style="margin-bottom: 20px;">
                    <div class="card" style="width: 18rem;">
                   
                        <img src="{{ asset('uploads/images/product/' ~ produit.images[0].name)|imagine_filter('square') }}" class="card-img-top" alt="{{produit.designation}}">
                       
                    
                        <div class="card-body">
                            <h5 class="card-title">{{produit.designation}}</h5>
                            <p class="card-text" style="color:red;">{{produit.remise}}%</p>
                            <p class="card-text">{{produit.prix}} DT</p>
                            <a href="{{ path('produit_detail', {'id': produit.id})}}" class="btn btn-primary">Détail</a>
                            <a href="{{ path('ajout_panier', {'id': produit.id})}}" class="btn btn-primary pull-right" >Panier </a>
                        </div>
                    </div>
                </div>
             {% endfor %}
        </div>
    
    

{% endblock %}

templates/home/panier.html.twig
{% extends 'front.html.twig' %}

{% block title %}Pannier!
{% endblock %}

{% block body %}
	<div class="alert alert-dismissible alert-info">
		<h1>Votre panier</h1>
	</div>
	{% if paniers |length >0 %}

		<table class="table">
			<tr class="table-info">
				<th>Produit</th>
				<th>Prix</th>
				<th>Quantité</th>
				<th>Total</th>
				<th></th>
			</tr>
			<tbody>
				{% for panier in paniers %}
					<tr class="table-success">
						<td>{{panier.produit.designation}}</td>
						<td>{{panier.produit.prix}}</td>
						<td>{{panier.quantite}}</td>
						<td>{{panier.produit.prix * panier.quantite}}</td>

						<td>
							
							<a href="{{path("prod_add", {id: panier.produit.id})}}" class="btn btn-success">
								<i class="fas fa-plus"></i>
							</a>
							<a href="{{path("prod_remove", {id: panier.produit.id})}}" class="btn btn-warning">
								<i class="fas fa-window-minimize"></i>
							</a>
							<a href="{{path("delete_prod", {id: panier.produit.id})}}" class="btn btn-danger">
								<i class="fas fa-trash"></i>
							</a>
						</td>

					</tr>
				{% endfor %}
			</tbody>
			<tfoot>
				<tr>
					<td colspan="3" class="text-right">Total:
					</td>
					<td>{{total }}</td>
				</tr>
			</tfoot>
		</table>

	{% else %}
		<div class="alert alert-dismissible alert-success">
			<strong>Oppss, c'est vide !</strong>
		</div>

	{% endif %}

{% endblock %}